### PR TITLE
Added quotes to escape special characters

### PR DESCRIPTION
**Pull request by prankymat**
``` bash
$ say -v Daniel Would you like a cup of tea?
```
will not run unless quotes are added around the sentence.

### CODE REVIEW

**Comment by cpmsmith** [comment]
It works fine without on my system. Zsh 5.1.1/Bash 3.2, OS X 10.11.4. 😕

**Comment by christiangenco** [comment]
Works for me on bash, but not Zsh:

```
bash-3.2$ say -v Daniel Would you like a cup of tea?
zsh5.0.7$ say -v Daniel Would you like a cup of tea?
zsh: no matches found: tea?
```

**Comment by prankymat** [comment]
Will therefore be better to have quotes around for this to work across shells.

**Comment by jbranchaud** [comment]
@prankymat Good catch, thanks for the fix.

**Pull request merged**
