### PR TITLE
unrar/rar on mac and linux

### PR DESCRIPTION
**Pull request by kunalshah**
added installation steps for unrar/rar on mac and linux

### CODE REVIEW

**Comment by kunalshah** [comment]
You are comparing raw file vs rendered file! That's not how it should be! When I submitted the pull request, it's not in markdown format. Rendered version looks like this: https://github.com/kunalshah/til/blob/unrar/linux/install-unrar.md

Look at the github markdown by clicking on the link "Styling with Markdown is supported
Comment Close and comment" on this page and look at the Code section; or look at here: https://guides.github.com/features/mastering-markdown/

**Comment by kunalshah** [comment]
The purpose of this markdown is to view it through github and that's why the author created files in markdown format.

**Comment by penne12** [comment]
Huh?

https://raw.githubusercontent.com/jbranchaud/til/master/linux/upgrading-ubuntu.md

is rendered as

https://github.com/jbranchaud/til/blob/master/linux/upgrading-ubuntu.md

So you write the raw version - and then GitHub renders it.

**Comment by kunalshah** [comment]
exactly, github renders raw markdown (.md) file  into equivalent html when it displays in browser (https://github.com/jbranchaud/til/blob/master/linux/upgrading-ubuntu.md) but the actual file contents are in markdown format (https://raw.githubusercontent.com/jbranchaud/til/master/linux/upgrading-ubuntu.md).

**Comment by kunalshah** [comment]
Well, I think you don't get it. I'll wait for the author to respond.

**Comment by penne12** [comment]
Oh - sorry - thought I saw 4 spaces, not the 2 you used. I feel bad now.

**Comment by kunalshah** [comment]
never mind, we're cool. Will wait for Josh to review the pull request.

**Comment by felipesabino** [comment]
@kunalshah Aren't you missing adding an entry to the README.md file at the [Linux section](https://github.com/jbranchaud/til#linux)?

**Comment by jbranchaud** [comment]
@kunalshah thanks for wanting to contribute! I want to continue to use this repo as my own collection of TILs. I think your content would be a great contribution to [til-collective](https://github.com/til-collective/til-collective) though. Check out the [til-collective contributing guidelines](https://github.com/til-collective/til-collective/blob/master/CONTRIBUTING.md) for more details.

**Comment by kunalshah** [comment]
@felipesabino , you are right. I missed it. Will include it in a new pull request.
@jbranchaud , got it. I am going to cancel the pull request and create another one.

**Pull request closed without merging**
